#!/usr/bin/env node
require.paths.unshift(__dirname + '/deps');
var ua3 = require('./server');

ua3.startup();

var reporter = require('./nodeunit').reporters.html;
console.log('ua3 started up, waiting 5 seconds before testing');
setTimeout(function(){ reporter.run(['tests']) }, 5000);
